#!/bin/bash
#SBATCH --quotatype auto
#SBATCH --partition NLP
#SBATCH --gres gpu:4
#SBATCH --nodes 1
#SBATCH -o phoenix-slurm-%j.out
# args: --quotatype=auto
# args: -p
# args: NLP
# args: --gres=gpu:4
# args: -N1
# args: bash
# args: ./scripts/dist_train.sh
# args: 4
# args: 15558
# args: --config
# args: ./cfgs/PCN_models/PoinTr.yaml
# args: --exp_name
# args: vanilla_in1536_out3584
# args: --save_dir
# args: s3://NLP/jsy/checkpoints/pointr_experiments
argv=()
while read -r line; do
    if [[ $line == "# args: "* ]]; then
        argv[${#argv[*]}]="${line:8}"
    fi
done < $0

srun "${argv[@]}"
